hw3-done, hw4-fixed
Alex-Shev75/Python-homework-repository pull request #1
Opened 2022-12-10 21:53 UTC by Alex-Shev75

ready for review

2022-12-10 21:54 UTC, Alex-Shev75 commented
Alexey,  check pls

2022-12-10 22:09 UTC, Alex-Shev75 commented
Alexey, i created one repository for all homework and added 3 and 4 work here. Check pls

2022-12-11 20:21 UTC, klymenok requested changes
Good, but pay attention to the comment

2022-12-11 20:21 UTC, klymenok commented on hw4/hw-lesson-4.py
> +    x = text % 2
There is no big need to create a separate variable here. You can put `text % 2` right into `if` condition

2022-12-11 20:51 UTC, Alex-Shev75 commented
fixed

2022-12-13 20:08 UTC, Alex-Shev75 commented
hw4 fixed, hw5 added for review

2022-12-23 20:45 UTC, merged