Homeworks 9
Alex-Shev75/Python-homework-repository pull request #8
Opened 2023-01-18 21:46 UTC by Alex-Shev75

part 1

2023-01-18 21:47 UTC, cyberdayag commented
Oleksii, i did not have time to complete 2 task. I will finish in a few days and add.

2023-01-18 23:37 UTC, Alex-Shev75 commented
added 2nd task

2023-01-19 20:03 UTC, Alex-Shev75 commented
added 3d task

2023-01-22 13:19 UTC, klymenok requested changes

2023-01-22 13:19 UTC, klymenok commented on hw9/phone_book_json.py
> +with open('json_pb.json', 'r+') as file_open:
Add here a check if the file exists because otherwise your program fails if there is no file yet

2023-01-22 13:19 UTC, klymenok commented on hw9/my_exception.py
> +class MyException:
You are confused a context manager and a custom exception. Your custom exception should look like this:
```
class MyCustomException(Exception):
    def __init__(self, message):
        # write to a file here

2023-01-22 13:19 UTC, klymenok commented on hw9/deco_file.py
> +        func(*args, **kwargs)
assign a result of `func` call to some variable and return it after the last print here to be able to decorate functions that return some value

2023-01-22 13:19 UTC, klymenok commented on hw9/deco_file.py
> +        with open('deco.txt', 'x') as deco_file:
With the `x` modifier this decorator will be able to log only once. Change it to `a+`

2023-01-22 13:19 UTC, klymenok commented on hw9/phone_book_json.py
> +                with open('json_pb.json', 'w') as file_add:
You will get an error if the file does not exist. Change the modifier to w+ to avoid this problem

2023-01-29 19:25 UTC, Alex-Shev75 commented
fixed

2023-02-02 21:39 UTC, klymenok requested changes

2023-02-02 21:39 UTC, klymenok commented on hw9/deco_file.py
> +        func(*args, **kwargs)
Remove this line (line 8) since you return the function call at the line 12

2023-02-02 21:39 UTC, klymenok commented on hw8/my_exception_class.py
> +class MyCustomException:
You implemented here a context manager, but the task was to take your `Custom Exception` and add a log record there.

2023-02-02 21:39 UTC, klymenok commented on hw9/phone_book_json.py
> +try:
You don't need to open the file twice here. It is enough to try to open in once and if the file does not exist you can initialize your `my_phone_book` dict as an empty dictionary.
Also, to read and transform your data to a dict you need:
- read a data from file: `data = file.read()`
- load data from json format using json lib: `my_phone_book` = json.loads(data)`

as the result, you will have something like this:
```
try:
    with open('json_pb.json', 'r+') as file_open:
        data = file.read()
        my_phone_book = json.loads(data)
except FileExistsError:
    my_phone_book = {}

2023-02-13 20:21 UTC, merged